// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webAPI;

namespace webAPI.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DersOgrenci", b =>
                {
                    b.Property<int>("aldigiDerslerid")
                        .HasColumnType("int");

                    b.Property<int>("dOgrencilerid")
                        .HasColumnType("int");

                    b.HasKey("aldigiDerslerid", "dOgrencilerid");

                    b.HasIndex("dOgrencilerid");

                    b.ToTable("DersOgrenci");
                });

            modelBuilder.Entity("webAPI.Models.Ders", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("dHocaid")
                        .HasColumnType("int");

                    b.Property<string>("dersKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("kontenjan")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("dHocaid");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("webAPI.Models.Ogrenci", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("ogrNo")
                        .HasColumnType("int");

                    b.Property<string>("soyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("webAPI.Models.OgretimUyesi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("persNo")
                        .HasColumnType("int");

                    b.Property<string>("soyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Hocalar");
                });

            modelBuilder.Entity("DersOgrenci", b =>
                {
                    b.HasOne("webAPI.Models.Ders", null)
                        .WithMany()
                        .HasForeignKey("aldigiDerslerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webAPI.Models.Ogrenci", null)
                        .WithMany()
                        .HasForeignKey("dOgrencilerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("webAPI.Models.Ders", b =>
                {
                    b.HasOne("webAPI.Models.OgretimUyesi", "dHoca")
                        .WithMany("verdigiDersler")
                        .HasForeignKey("dHocaid");

                    b.Navigation("dHoca");
                });

            modelBuilder.Entity("webAPI.Models.OgretimUyesi", b =>
                {
                    b.Navigation("verdigiDersler");
                });
#pragma warning restore 612, 618
        }
    }
}
